<!--
Name: 710sRice
IsDark: {{_isDark}}
HasBlur: False
GENERATED by tools\apply-wallust-outputs.ps1 from the active palette profile; do not hand-edit
(change the profile: SUPER+Alt+Space > Palette profiles). Ported from winarchy's
templates/flow-theme.xaml.tpl. The three lines above are Flow's own theme metadata.
(No double hyphen anywhere in this comment: XML forbids one, and Flow can't read a bad theme.)
-->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/Themes/Base.xaml" />
    </ResourceDictionary.MergedDictionaries>
    <Thickness x:Key="ResultMargin">0 0 0 6</Thickness>
    <Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
        <Setter Property="Background" Value="{{window}}" />
        <Setter Property="Foreground" Value="{{query}}" />
        <Setter Property="CaretBrush" Value="{{caret}}" />
        <Setter Property="SelectionBrush" Value="{{selection}}" />
    </Style>
    <Style x:Key="QuerySuggestionBoxStyle" BasedOn="{StaticResource BaseQuerySuggestionBoxStyle}" TargetType="{x:Type TextBox}">
        <Setter Property="Background" Value="{{window}}" />
        <Setter Property="Foreground" Value="{{suggestion}}" />
    </Style>
    <Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="Background" Value="{{window}}" />
        <Setter Property="BorderBrush" Value="{{border}}" />
        <Setter Property="BorderThickness" Value="1" />
        <Setter Property="CornerRadius" Value="8" />
    </Style>
    <Style x:Key="WindowStyle" BasedOn="{StaticResource BaseWindowStyle}" TargetType="{x:Type Window}" />
    <Style x:Key="PendingLineStyle" BasedOn="{StaticResource BasePendingLineStyle}" TargetType="{x:Type Line}">
        <Setter Property="Stroke" Value="{{border}}" />
    </Style>
    <Style x:Key="ItemTitleStyle" BasedOn="{StaticResource BaseItemTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{title}}" />
    </Style>
    <Style x:Key="ItemSubTitleStyle" BasedOn="{StaticResource BaseItemSubTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="ItemTitleSelectedStyle" BasedOn="{StaticResource BaseItemTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{selectedTitle}}" />
    </Style>
    <Style x:Key="ItemSubTitleSelectedStyle" BasedOn="{StaticResource BaseItemSubTitleSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{selectedTitle}}" />
    </Style>
    <Style x:Key="ItemHotkeyStyle" BasedOn="{StaticResource BaseItemHotkeyStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="ItemHotkeySelectedStyle" BasedOn="{StaticResource BaseItemHotkeySelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{selectedTitle}}" />
    </Style>
    <Style x:Key="HighlightStyle">
        <Setter Property="Inline.FontWeight" Value="Bold" />
        <Setter Property="TextElement.Foreground" Value="{{highlight}}" />
    </Style>
    <SolidColorBrush x:Key="ItemSelectedBackgroundColor">{{selected}}</SolidColorBrush>
    <Style x:Key="ItemGlyph" BasedOn="{StaticResource BaseGlyphStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{title}}" />
    </Style>
    <Style x:Key="ItemGlyphSelectedStyle" BasedOn="{StaticResource BaseGlyphSelectedStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{selectedTitle}}" />
    </Style>
    <Style x:Key="ItemNumberStyle" BasedOn="{StaticResource BaseItemNumberStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="ItemImageSelectedStyle" BasedOn="{StaticResource BaseItemImageSelectedStyle}" TargetType="{x:Type Image}">
        <Setter Property="Cursor" Value="Arrow" />
    </Style>
    <Style x:Key="ThumbStyle" BasedOn="{StaticResource BaseThumbStyle}" TargetType="{x:Type Thumb}">
        <Setter Property="Width" Value="2" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="{x:Type Thumb}">
                    <Border Background="{{subtitle}}" BorderThickness="0" CornerRadius="2" DockPanel.Dock="Right" />
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
    <Style x:Key="ScrollBarStyle" BasedOn="{StaticResource BaseScrollBarStyle}" TargetType="{x:Type ScrollBar}" />
    <Style x:Key="SeparatorStyle" BasedOn="{StaticResource BaseSeparatorStyle}" TargetType="{x:Type Rectangle}">
        <Setter Property="Fill" Value="{{separator}}" />
        <Setter Property="Height" Value="1" />
        <Setter Property="Margin" Value="12 0 12 6" />
    </Style>
    <Style x:Key="SearchIconStyle" BasedOn="{StaticResource BaseSearchIconStyle}" TargetType="{x:Type Path}">
        <Setter Property="Fill" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="ClockBox" BasedOn="{StaticResource BaseClockBox}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="DateBox" BasedOn="{StaticResource BaseDateBox}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="PreviewBorderStyle" BasedOn="{StaticResource BasePreviewBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="BorderBrush" Value="{{separator}}" />
    </Style>
    <Style x:Key="PreviewItemTitleStyle" BasedOn="{StaticResource BasePreviewItemTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{title}}" />
    </Style>
    <Style x:Key="PreviewItemSubTitleStyle" BasedOn="{StaticResource BasePreviewItemSubTitleStyle}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{subtitle}}" />
    </Style>
    <Style x:Key="PreviewGlyph" BasedOn="{StaticResource BasePreviewGlyph}" TargetType="{x:Type TextBlock}">
        <Setter Property="Foreground" Value="{{title}}" />
    </Style>
</ResourceDictionary>
