/* GENERATED by tools\apply-wallust-outputs.ps1 from the active palette profile -- do not
   hand-edit (change the profile: SUPER+Alt+Space > Palette profiles).
   710.ahk's menus and the palette editor read these; the names match the bar's file so
   either one can stand in for the other. */
:root {
    --wallust-background: {{background}};
    --wallust-text: {{text}};
    --wallust-accent: {{accent}};
    --wallust-selectedText: {{selectedText}};
    --wallust-subtext: {{subtext}};
}
