#Requires -Version 7.0
<#
.SYNOPSIS
  Writes config\wallust\wallust.toml from config\wallust\wallust.template.toml, with this
  repo's real location filled in.

.DESCRIPTION
  wallust's [templates] targets have to be absolute paths, and this repo can be cloned
  anywhere, so the tracked file is a template with {{DESKTOPRICE_HOME}} placeholders and
  this fills them in -- same idea as komorebi.json being compiled from base.json. Run by
  install.ps1 (before its first `wallust run`); safe to run by hand any time, e.g. after
  editing the template. Only rewrites the file when the result would actually change.
  The output is gitignored.

  Exit codes: 0 = written, or already current; 1 = template missing, unusable repo path,
  or the write failed.

  -Check (`710sRice doctor`): the same comparison, nothing written. Exit 0 = current,
  3 = it would be written (missing, or generated for another location); 1 as above.
#>
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$Root     = Split-Path -Parent $PSScriptRoot
$dir      = Join-Path $Root 'config\wallust'
$template = Join-Path $dir 'wallust.template.toml'
$target   = Join-Path $dir 'wallust.toml'

# Paths in messages are repo-relative: the clone may sit under the user's own folders, and
# doctor shows these warnings in its report.
if (-not (Test-Path $template)) { Write-Warning "wallust template not found: config\wallust\wallust.template.toml"; exit 1 }
# The template's paths are TOML literal strings ('...'), which can't contain a single
# quote -- a repo path with one would give wallust a config it can't parse. Say so plainly
# instead of writing a broken file.
if ($Root.Contains("'")) {
    Write-Warning "This clone's path contains a single quote, which wallust.toml's literal strings can't hold -- clone it somewhere without one."
    exit 1
}

$content = "# GENERATED by tools\write-wallust-config.ps1 from wallust.template.toml -- edit the template, not this file.`n" +
           (Get-Content $template -Raw -Encoding UTF8).Replace('{{DESKTOPRICE_HOME}}', $Root)

if ((Test-Path $target) -and
    (((Get-Content $target -Raw -Encoding UTF8) -replace "`r`n", "`n") -eq ($content -replace "`r`n", "`n"))) {
    Write-Host "wallust.toml already current for this clone"
    exit 0
}
if ($Check) { exit 3 }   # read-only: it would be written
try {
    [System.IO.File]::WriteAllText($target, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "wallust.toml written for this clone"
} catch {
    Write-Warning "couldn't write config\wallust\wallust.toml: $($_.Exception.Message)"
    exit 1
}
exit 0
