# GENERATED by wallust -- do not hand-edit, re-run wallust (change the wallpaper) to
# regenerate. Personalization goes in config/pwsh/user.ps1 (e.g. your own $env:STARSHIP_CONFIG
# pointing elsewhere), which loads after this and overrides it.
#
# Structure ported from winarchy's config/pwsh/starship.toml @ 4574fc7 (tag v1.4.0), but
# recolored to this repo's shared wallust accent (color3) instead of winarchy's several
# separate hardcoded hues -- same "matchy-matchy" one-accent-everywhere design as
# config/yasb/wallust_colors.css and tools/apply-wallust-outputs.ps1's komorebi border /
# Windows accent / Windows Terminal scheme. Error/failure states are intentionally NOT
# wallust-driven (fixed red) -- same reasoning as styles.css's redFlash: an alert should
# read as "red" no matter which wallpaper palette is active.

add_newline = true
scan_timeout = 100

format = """
$directory$git_branch$git_status$git_state$cmd_duration$python$nodejs$rust
$character"""

[character]
success_symbol = "[❯](bold {{color3}})"
error_symbol = "[❯](bold #d35f5f)"

[directory]
style = "bold {{color3}}"
truncation_length = 4
truncate_to_repo = true
format = " [$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "bold {{color7}}"
format = "[$symbol$branch]($style) "

[git_status]
style = "{{color5}}"
format = "([$all_status$ahead_behind]($style) )"

[git_state]
style = "bold #d35f5f"

[cmd_duration]
min_time = 2000
style = "{{color5}}"
format = "[⏱ $duration]($style) "

[status]
disabled = false
style = "bold #d35f5f"

[python]
style = "{{color6}}"
format = "[$symbol$version]($style) "

[nodejs]
style = "{{color6}}"
format = "[$symbol$version]($style) "

[rust]
style = "{{color6}}"
format = "[$symbol$version]($style) "

[package]
disabled = true
