/* GENERATED by wallust — do not hand-edit, re-run wallust to regenerate.
   Full-palette slot mapping (deliberately explicit, easy to re-point):
     --wallust-background  <- color1  (near-dark, wallpaper-tinted, not pure black)
     --wallust-background2 <- color2  (secondary panel bg, same slot as mutedBG/border)
     --wallust-accent      <- color3  (the one shared accent slot every consumer uses)
     --wallust-text        <- color6  (near-light, wallpaper-tinted, not pure white)
     --wallust-accentText  <- color7  (lightest — readable on top of the mid-tone accent)
     --wallust-hover       <- color4
     --wallust-mutedBG     <- color2  (matches background2/border, same as the old scheme)
     --wallust-border      <- color2
     --wallust-subtext     <- color5
   redFlash is intentionally NOT wallust-driven (see styles.css) — an alert color
   should read as "red" regardless of which wallpaper/palette is active. */
:root {
    --wallust-background: {{color1}};
    --wallust-background2: {{color2}};
    --wallust-accent: {{color3}};
    --wallust-text: {{color6}};
    --wallust-accentText: {{color7}};
    --wallust-hover: {{color4}};
    --wallust-mutedBG: {{color2}};
    --wallust-border: {{color2}};
    --wallust-subtext: {{color5}};
}
